### Importando Bibliotecas ###

In [3]:
import pandas as pd
import numpy as np

### Coletando as planilhas das ligas Principais  ###

In [4]:
# Inglaterra 1

ENG1_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv') # Campeonato Inglês 2023/2024
ENG1_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/E0.csv') # Campeonato Inglês 2023/2024
ENG1_11 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/E0.csv') # Campeonato Inglês 2024/2025
ENG1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv") # Campeonato Inglês 2021/2022
ENG1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv") # Campeonato Inglês 2020/2021
ENG1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E0.csv") # Campeonato Inglês 2019/2020
ENG1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E0.csv") # Campeonato Inglês 2018/2019
ENG1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E0.csv") # Campeonato Inglês 2017/2018
ENG1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/E0.csv") # Campeonato Inglês 2016/2017
ENG1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/E0.csv") # Campeonato Inglês 2015/2016
ENG1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/E0.csv") # Campeonato Inglês 2014/2015
ENG1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/E0.csv") # Campeonato Inglês 2013/2014
ENG1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/E0.csv") # Campeonato Inglês 2012/2013

ENG1 = [ENG1_01,ENG1_02,ENG1_03,ENG1_04,ENG1_05,ENG1_06,ENG1_07,ENG1_08,ENG1_09,ENG1_10, ENG1_11, ENG1_12, ENG1_13]
ENG1 = pd.concat(ENG1)
ENG1['Liga'] = 'Inglaterra 1'

# Inglaterra 2

ENG2_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E1.csv') # Campeonato Inglês 2023/2024
ENG2_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/E1.csv') # Campeonato Inglês 2023/2024
ENG2_11 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/E1.csv') # Campeonato Inglês 2024/2025
ENG2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv") # Campeonato Inglês 2021/2022
ENG2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E1.csv") # Campeonato Inglês 2020/2021
ENG2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E1.csv") # Campeonato Inglês 2019/2020
ENG2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E1.csv") # Campeonato Inglês 2018/2019
ENG2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E1.csv") # Campeonato Inglês 2017/2018
ENG2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/E1.csv") # Campeonato Inglês 2016/2017
ENG2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/E1.csv") # Campeonato Inglês 2015/2016
ENG2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/E1.csv") # Campeonato Inglês 2014/2015
ENG2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/E1.csv") # Campeonato Inglês 2013/2014
ENG2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/E1.csv") # Campeonato Inglês 2012/2013

ENG2 = [ENG2_01,ENG2_02,ENG2_03,ENG2_04,ENG2_05,ENG2_06,ENG2_07,ENG2_08,ENG2_09,ENG2_10, ENG2_11, ENG2_12, ENG2_13]
ENG2 = pd.concat(ENG2)
ENG2['Liga'] = 'Inglaterra 2'


# Alemanha 1

GER1_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/D1.csv')
GER1_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/D1.csv')
GER1_11 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/D1.csv')
GER1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D1.csv")
GER1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D1.csv")
GER1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D1.csv")
GER1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D1.csv")
GER1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D1.csv")
GER1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/D1.csv")
GER1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/D1.csv")
GER1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/D1.csv")
GER1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/D1.csv")
GER1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/D1.csv")
GER1 = [GER1_01,GER1_02,GER1_03,GER1_04,GER1_05,GER1_06,GER1_07,GER1_08,GER1_09,GER1_10, GER1_11, GER1_12, GER1_13]
GER1 = pd.concat(GER1)
GER1['Liga'] = 'Alemanha 1'

# Alemanha 2

GER2_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/D2.csv')
GER2_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/D2.csv')
GER2_11 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/D2.csv')
GER2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D2.csv")
GER2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D2.csv")
GER2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D2.csv")
GER2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D2.csv")
GER2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D2.csv")
GER2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/D2.csv")
GER2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/D2.csv")
GER2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/D2.csv")
GER2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/D2.csv")
GER2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/D2.csv")
GER2 = [GER2_01,GER2_02,GER2_03,GER2_04,GER2_05,GER2_06,GER2_07,GER2_08,GER2_09,GER2_10, GER2_11, GER2_12, GER2_13]
GER2 = pd.concat(GER2)
GER2['Liga'] = 'Alemanha 2'

# Itália 1

ITA1_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/I1.csv')
ITA1_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/I1.csv')
ITA1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/I1.csv")
ITA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv")
ITA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I1.csv")
ITA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I1.csv")
ITA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/I1.csv")
ITA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I1.csv")
ITA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/I1.csv")
ITA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/I1.csv")
ITA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/I1.csv")
ITA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/I1.csv")
ITA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/I1.csv")
ITA1 = [ITA1_01,ITA1_02,ITA1_03,ITA1_04,ITA1_05,ITA1_06,ITA1_07,ITA1_08,ITA1_09,ITA1_10, ITA1_11, ITA1_12, ITA1_13]
ITA1 = pd.concat(ITA1)
ITA1['Liga'] = 'Itália 1'

# Itália 2

ITA2_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/I2.csv')
ITA2_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/I2.csv')
ITA2_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/I2.csv")
ITA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv")
ITA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I2.csv")
ITA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I2.csv")
# ITA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/I2.csv")
ITA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I2.csv")
ITA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/I2.csv")
ITA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/I2.csv")
ITA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/I2.csv")
ITA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/I2.csv")
ITA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/I2.csv")
ITA2 = [ITA2_01,ITA2_02,ITA2_03,ITA2_05,ITA2_06,ITA2_08,ITA2_09,ITA2_10, ITA2_11, ITA2_12, ITA2_13]
ITA2 = pd.concat(ITA2)
ITA2['Liga'] = 'Itália 2'

# Espanha 1

SPA1_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/SP1.csv')
SPA1_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/SP1.csv')
SPA1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/SP1.csv")
SPA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv")
SPA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP1.csv")
SPA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP1.csv")
SPA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP1.csv")
SPA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP1.csv")
SPA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SP1.csv")
SPA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/SP1.csv")
SPA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/SP1.csv")
SPA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/SP1.csv")
SPA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/SP1.csv")
SPA1 = [SPA1_01,SPA1_02,SPA1_03,SPA1_04,SPA1_05,SPA1_06,SPA1_07,SPA1_08,SPA1_09,SPA1_10, SPA1_11, SPA1_12, SPA1_13]
SPA1 = pd.concat(SPA1)
SPA1['Liga'] = 'Espanha 1'

# Espanha 2
SPA2_13 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/SP2.csv')
SPA2_12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/SP2.csv')
SPA2_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/SP2.csv")
SPA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv")
SPA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP2.csv")
SPA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP2.csv")
SPA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP2.csv")
SPA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP2.csv")
SPA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SP2.csv")
SPA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/SP2.csv")
SPA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/SP2.csv")
SPA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/SP2.csv")
SPA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/SP2.csv")
SPA2 = [SPA2_01,SPA2_02,SPA2_03,SPA2_04,SPA2_05,SPA2_06,SPA2_07,SPA2_08,SPA2_09,SPA2_10, SPA2_11, SPA2_12, SPA2_13]
SPA2 = pd.concat(SPA2)
SPA2['Liga'] = 'Espanha 2'

# França 1
FRA1_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/F1.csv")
FRA1_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/F1.csv")
FRA1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/F1.csv")
FRA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv")
FRA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F1.csv")
FRA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F1.csv")
FRA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F1.csv")
FRA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F1.csv")
FRA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/F1.csv")
FRA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/F1.csv")
FRA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/F1.csv")
FRA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/F1.csv")
FRA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/F1.csv")
FRA1 = [FRA1_01,FRA1_02,FRA1_03,FRA1_04,FRA1_05,FRA1_06,FRA1_07,FRA1_08,FRA1_09,FRA1_10, FRA1_11, FRA1_12, FRA1_13]
FRA1 = pd.concat(FRA1)
FRA1['Liga'] = 'França 1'

# França 2
FRA2_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/F2.csv")
FRA2_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/F2.csv")
FRA2_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/F2.csv")
FRA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv")
FRA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F2.csv")
FRA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F2.csv")
FRA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F2.csv")
FRA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F2.csv")
FRA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/F2.csv")
FRA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/F2.csv")
FRA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/F2.csv")
FRA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/F2.csv")
FRA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/F2.csv")
FRA2 = [FRA2_01,FRA2_02,FRA2_03,FRA2_04,FRA2_05,FRA2_06,FRA2_07,FRA2_08,FRA2_09,FRA2_10, FRA2_11, FRA2_12, FRA2_13]
FRA2 = pd.concat(FRA2)
FRA2['Liga'] = 'França 2'

# Holanda 1
NET1_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/N1.csv")
NET1_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/N1.csv")
NET1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/N1.csv")
NET1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/N1.csv")
NET1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/N1.csv")
NET1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/N1.csv")
NET1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/N1.csv")
NET1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/N1.csv")
NET1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/N1.csv")
NET1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/N1.csv")
NET1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/N1.csv")
NET1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/N1.csv")
NET1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/N1.csv")
NET1 = [NET1_01,NET1_02,NET1_03,NET1_04,NET1_05,NET1_06,NET1_07,NET1_08,NET1_09,NET1_10, NET1_11, NET1_12, NET1_13]
NET1 = pd.concat(NET1)
NET1['Liga'] = 'Holanda 1'

# Bélgica 1
BEL1_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/B1.csv")
BEL1_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/B1.csv")
BEL1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/B1.csv")
BEL1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/B1.csv")
BEL1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/B1.csv")
BEL1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/B1.csv")
BEL1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/B1.csv")
BEL1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/B1.csv")
BEL1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/B1.csv")
BEL1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/B1.csv")
BEL1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/B1.csv")
BEL1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/B1.csv")
BEL1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/B1.csv")
BEL1 = [BEL1_01,BEL1_02,BEL1_03,BEL1_04,BEL1_05,BEL1_06,BEL1_07,BEL1_08,BEL1_09,BEL1_10, BEL1_11, BEL1_12, BEL1_13]
BEL1 = pd.concat(BEL1)
BEL1['Liga'] = 'Bélgica 1'

# Portugal 1
POR1_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/P1.csv")
POR1_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/P1.csv")
POR1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/P1.csv")
POR1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/P1.csv")
POR1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/P1.csv")
POR1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/P1.csv")
POR1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/P1.csv")
POR1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/P1.csv")
POR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/P1.csv")
POR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/P1.csv")
POR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/P1.csv")
POR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/P1.csv")
POR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/P1.csv")
POR1 = [POR1_01,POR1_02,POR1_03,POR1_04,POR1_05,POR1_06,POR1_07,POR1_08,POR1_09,POR1_10, POR1_11, POR1_12, POR1_13]
POR1 = pd.concat(POR1)
POR1['Liga'] = 'Portugal 1'

# Turquia 1
TUR1_13 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/T1.csv")
TUR1_12 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/T1.csv")
TUR1_11 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/T1.csv")
TUR1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/T1.csv")
TUR1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/T1.csv")
TUR1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/T1.csv")
TUR1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/T1.csv")
TUR1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/T1.csv")
TUR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/T1.csv")
TUR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/T1.csv")
TUR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/T1.csv")
TUR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/T1.csv")
TUR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/T1.csv")
TUR1 = [TUR1_01,TUR1_02,TUR1_03,TUR1_04,TUR1_05,TUR1_06,TUR1_07,TUR1_08,TUR1_09,TUR1_10,TUR1_11,TUR1_12,TUR1_13]
TUR1 = pd.concat(TUR1)
TUR1['Liga'] = 'Turquia 1'

C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ENG1['Liga'] = 'Inglaterra 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ENG2['Liga'] = 'Inglaterra 2'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  GER1['Liga'] = 'Alemanha 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  GER2['Liga'] = 'Alemanha 2'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ITA1['Liga'] = 'Itália 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:116: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ITA2['Liga'] = 'Itália 2'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  SPA1['Liga'] = 'Espanha 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:153: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  SPA2['Liga'] = 'Espanha 2'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:171: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  FRA1['Liga'] = 'França 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  FRA2['Liga'] = 'França 2'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:207: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  NET1['Liga'] = 'Holanda 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:225: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BEL1['Liga'] = 'Bélgica 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:243: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  POR1['Liga'] = 'Portugal 1'
C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1881873980.py:261: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  TUR1['Liga'] = 'Turquia 1'

Coletando as planilhas das Ligas Secundárias

In [5]:
ARG = pd.read_csv("https://www.football-data.co.uk/new/ARG.csv")
ARG['Liga'] = 'Argentina'

AUS = pd.read_csv("https://www.football-data.co.uk/new/AUT.csv")
AUS['Liga'] = 'Austria'

BRA = pd.read_csv("https://www.football-data.co.uk/new/BRA.csv")
BRA['Liga'] = 'Brasil'

CHI = pd.read_csv("https://www.football-data.co.uk/new/CHN.csv")
CHI['Liga'] = 'China'

DIN = pd.read_csv("https://www.football-data.co.uk/new/DNK.csv")
DIN['Liga'] = 'Dinamarca'

FIN = pd.read_csv("https://www.football-data.co.uk/new/FIN.csv")
FIN['Liga'] = 'Finlândia'

IRL = pd.read_csv("https://www.football-data.co.uk/new/IRL.csv")
IRL['Liga'] = 'Irlanda'

JAP = pd.read_csv("https://www.football-data.co.uk/new/JPN.csv")
JAP['Liga'] = 'Japão'

MEX = pd.read_csv("https://www.football-data.co.uk/new/MEX.csv")
MEX['Liga'] = 'México'

NOR = pd.read_csv("https://www.football-data.co.uk/new/NOR.csv")
NOR['Liga'] = 'Noruega'

POL = pd.read_csv("https://www.football-data.co.uk/new/POL.csv")
POL['Liga'] = 'Polônia'

ROM = pd.read_csv("https://www.football-data.co.uk/new/ROU.csv")
ROM['Liga'] = 'Romêmia'

RUS = pd.read_csv("https://www.football-data.co.uk/new/RUS.csv")
RUS['Liga'] = 'Rússia'

SUE = pd.read_csv("https://www.football-data.co.uk/new/SWE.csv")
SUE['Liga'] = 'Suécia'

SUI = pd.read_csv("https://www.football-data.co.uk/new/SWZ.csv")
SUI['Liga'] = 'Suíça'

USA = pd.read_csv("https://www.football-data.co.uk/new/USA.csv")
USA['Liga'] = 'USA'

Concatenando as Planilhas

In [6]:
df1 = [ENG1, ENG2, GER1, GER2, ITA1, ITA2, SPA1, SPA2, FRA1, FRA2, NET1, BEL1, POR1, TUR1]
df1 = pd.concat(df1)

df2 = [ARG, AUS, BRA, CHI, DIN, FIN, IRL, JAP, MEX, NOR, POL, ROM, RUS, SUE, SUI, USA]
df2 = pd.concat(df2)

Selecionando as colunas que serão utilizadas

In [7]:
df1 = df1[['Liga','Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','B365H','B365D','B365A']]

df2 = df2[['Country','Date', 'Home', 'Away', 'HG', 'AG', 'Res','PSCH','PSCD','PSCA']]

df1['Date'] = pd.to_datetime(df1.Date)
df1['Date'] = pd.to_datetime(df1.Date)

C:\Users\Home\AppData\Local\Temp\ipykernel_10868\1044503236.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['Date'] = pd.to_datetime(df1.Date)

Renomeando as Colunas e unindo os DataFrames

In [8]:
df1.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df2.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df = [df1, df2]
df = pd.concat(df)

Visualizando o Resultado Final

In [9]:
df

,Liga,Data,Mandante,Visitante,Gols Mandante,Gols Visitante,Resultado,Odds Mandante,Odds Empate,Odds Visitante
0,Inglaterra 1,2012-08-18 00:00:00,Arsenal,Sunderland,0.0,0.0,D,1.40,4.50,8.50
1,Inglaterra 1,2012-08-18 00:00:00,Fulham,Norwich,5.0,0.0,H,1.80,3.60,4.50
2,Inglaterra 1,2012-08-18 00:00:00,Newcastle,Tottenham,2.0,1.0,H,2.50,3.40,2.75
3,Inglaterra 1,2012-08-18 00:00:00,QPR,Swansea,0.0,5.0,A,2.00,3.40,3.80
4,Inglaterra 1,2012-08-18 00:00:00,Reading,Stoke,1.0,1.0,D,2.38,3.25,3.10
...,...,...,...,...,...,...,...,...,...,...
5264,USA,04/11/2024,Vancouver Whitecaps,Los Angeles FC,3.0,0.0,H,2.54,3.67,2.72
5265,USA,09/11/2024,Los Angeles FC,Vancouver Whitecaps,1.0,0.0,H,1.70,4.23,4.69
5266,USA,09/11/2024,FC Cincinnati,New York City,0.0,0.0,D,1.88,3.81,4.14
5267,USA,09/11/2024,Orlando City,Charlotte,1.0,1.0,D,1.78,3.92,4.61
5268,USA,10/11/2024,Inter Miami,Atlanta Utd,2.0,3.0,A,1.33,5.72,8.88

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117614 entries, 0 to 5268
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Liga            117614 non-null  object
 1   Data            117381 non-null  object
 2   Mandante        117381 non-null  object
 3   Visitante       117381 non-null  object
 4   Gols Mandante   117380 non-null  float64
 5   Gols Visitante  117380 non-null  float64
 6   Resultado       117380 non-null  object
 7   Odds Mandante   117089 non-null  float64
 8   Odds Empate     117089 non-null  float64
 9   Odds Visitante  117089 non-null  float64
dtypes: float64(5), object(5)
memory usage: 9.9+ MB

In [11]:
df.dropna()

,Liga,Data,Mandante,Visitante,Gols Mandante,Gols Visitante,Resultado,Odds Mandante,Odds Empate,Odds Visitante
0,Inglaterra 1,2012-08-18 00:00:00,Arsenal,Sunderland,0.0,0.0,D,1.40,4.50,8.50
1,Inglaterra 1,2012-08-18 00:00:00,Fulham,Norwich,5.0,0.0,H,1.80,3.60,4.50
2,Inglaterra 1,2012-08-18 00:00:00,Newcastle,Tottenham,2.0,1.0,H,2.50,3.40,2.75
3,Inglaterra 1,2012-08-18 00:00:00,QPR,Swansea,0.0,5.0,A,2.00,3.40,3.80
4,Inglaterra 1,2012-08-18 00:00:00,Reading,Stoke,1.0,1.0,D,2.38,3.25,3.10
...,...,...,...,...,...,...,...,...,...,...
5264,USA,04/11/2024,Vancouver Whitecaps,Los Angeles FC,3.0,0.0,H,2.54,3.67,2.72
5265,USA,09/11/2024,Los Angeles FC,Vancouver Whitecaps,1.0,0.0,H,1.70,4.23,4.69
5266,USA,09/11/2024,FC Cincinnati,New York City,0.0,0.0,D,1.88,3.81,4.14
5267,USA,09/11/2024,Orlando City,Charlotte,1.0,1.0,D,1.78,3.92,4.61
5268,USA,10/11/2024,Inter Miami,Atlanta Utd,2.0,3.0,A,1.33,5.72,8.88

In [12]:
df

,Liga,Data,Mandante,Visitante,Gols Mandante,Gols Visitante,Resultado,Odds Mandante,Odds Empate,Odds Visitante
0,Inglaterra 1,2012-08-18 00:00:00,Arsenal,Sunderland,0.0,0.0,D,1.40,4.50,8.50
1,Inglaterra 1,2012-08-18 00:00:00,Fulham,Norwich,5.0,0.0,H,1.80,3.60,4.50
2,Inglaterra 1,2012-08-18 00:00:00,Newcastle,Tottenham,2.0,1.0,H,2.50,3.40,2.75
3,Inglaterra 1,2012-08-18 00:00:00,QPR,Swansea,0.0,5.0,A,2.00,3.40,3.80
4,Inglaterra 1,2012-08-18 00:00:00,Reading,Stoke,1.0,1.0,D,2.38,3.25,3.10
...,...,...,...,...,...,...,...,...,...,...
5264,USA,04/11/2024,Vancouver Whitecaps,Los Angeles FC,3.0,0.0,H,2.54,3.67,2.72
5265,USA,09/11/2024,Los Angeles FC,Vancouver Whitecaps,1.0,0.0,H,1.70,4.23,4.69
5266,USA,09/11/2024,FC Cincinnati,New York City,0.0,0.0,D,1.88,3.81,4.14
5267,USA,09/11/2024,Orlando City,Charlotte,1.0,1.0,D,1.78,3.92,4.61
5268,USA,10/11/2024,Inter Miami,Atlanta Utd,2.0,3.0,A,1.33,5.72,8.88

Exportando o arquivo final para o Excel

In [14]:
df.to_excel('Base_De_Dados_Full.xlsx', index=False)